sudo: false
cache: bundler
language: ruby

bundler_args: --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - gem install bundler -v '< 2'

rvm:
- 3.0.1 
- 2.7.3

install:
  - bundle install
script:
  - bundle exec rspec
  - bundle exec rubocop
