sudo: false
cache: bundler
language: ruby

bundler_args: --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - gem install bundler -v '< 2'

rvm:
- 2.5.1
- 2.0.0
- 2.2
- 2.3.0
- 1.9.3
- jruby
- ruby-head
env:
  # this doesn't do anything for MRI or RBX, but it doesn't hurt them either
  # for JRuby, it enables us to get more accurate coverage data
  - JRUBY_OPTS="--debug"
matrix:
  allow_failures:
  - rvm: jruby
  - rvm: ruby-head

install:
  - bundle install
script:
  - bundle exec rspec
  - bundle exec rubocop
